# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nikolas/Programming/repos/fire-collector-bot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nikolas/Programming/repos/fire-collector-bot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikolas/Programming/repos/fire-collector-bot/CMakeFiles /home/nikolas/Programming/repos/fire-collector-bot//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikolas/Programming/repos/fire-collector-bot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named proj1.elf

# Build rule for target.
proj1.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 proj1.elf
.PHONY : proj1.elf

# fast build rule for target.
proj1.elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/build
.PHONY : proj1.elf/fast

#=============================================================================
# Target rules for targets named proj1.hex

# Build rule for target.
proj1.hex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 proj1.hex
.PHONY : proj1.hex

# fast build rule for target.
proj1.hex/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.hex.dir/build.make CMakeFiles/proj1.hex.dir/build
.PHONY : proj1.hex/fast

#=============================================================================
# Target rules for targets named proj1.bin

# Build rule for target.
proj1.bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 proj1.bin
.PHONY : proj1.bin

# fast build rule for target.
proj1.bin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.bin.dir/build.make CMakeFiles/proj1.bin.dir/build
.PHONY : proj1.bin/fast

CMSIS/core_cm3_linux.o: CMSIS/core_cm3_linux.c.o
.PHONY : CMSIS/core_cm3_linux.o

# target to build an object file
CMSIS/core_cm3_linux.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/CMSIS/core_cm3_linux.c.o
.PHONY : CMSIS/core_cm3_linux.c.o

CMSIS/core_cm3_linux.i: CMSIS/core_cm3_linux.c.i
.PHONY : CMSIS/core_cm3_linux.i

# target to preprocess a source file
CMSIS/core_cm3_linux.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/CMSIS/core_cm3_linux.c.i
.PHONY : CMSIS/core_cm3_linux.c.i

CMSIS/core_cm3_linux.s: CMSIS/core_cm3_linux.c.s
.PHONY : CMSIS/core_cm3_linux.s

# target to generate assembly for a file
CMSIS/core_cm3_linux.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/CMSIS/core_cm3_linux.c.s
.PHONY : CMSIS/core_cm3_linux.c.s

CMSIS/system_stm32f10x.o: CMSIS/system_stm32f10x.c.o
.PHONY : CMSIS/system_stm32f10x.o

# target to build an object file
CMSIS/system_stm32f10x.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/CMSIS/system_stm32f10x.c.o
.PHONY : CMSIS/system_stm32f10x.c.o

CMSIS/system_stm32f10x.i: CMSIS/system_stm32f10x.c.i
.PHONY : CMSIS/system_stm32f10x.i

# target to preprocess a source file
CMSIS/system_stm32f10x.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/CMSIS/system_stm32f10x.c.i
.PHONY : CMSIS/system_stm32f10x.c.i

CMSIS/system_stm32f10x.s: CMSIS/system_stm32f10x.c.s
.PHONY : CMSIS/system_stm32f10x.s

# target to generate assembly for a file
CMSIS/system_stm32f10x.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/CMSIS/system_stm32f10x.c.s
.PHONY : CMSIS/system_stm32f10x.c.s

Hardware/Bsp.o: Hardware/Bsp.c.o
.PHONY : Hardware/Bsp.o

# target to build an object file
Hardware/Bsp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Hardware/Bsp.c.o
.PHONY : Hardware/Bsp.c.o

Hardware/Bsp.i: Hardware/Bsp.c.i
.PHONY : Hardware/Bsp.i

# target to preprocess a source file
Hardware/Bsp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Hardware/Bsp.c.i
.PHONY : Hardware/Bsp.c.i

Hardware/Bsp.s: Hardware/Bsp.c.s
.PHONY : Hardware/Bsp.s

# target to generate assembly for a file
Hardware/Bsp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Hardware/Bsp.c.s
.PHONY : Hardware/Bsp.c.s

Hardware/CH452.o: Hardware/CH452.c.o
.PHONY : Hardware/CH452.o

# target to build an object file
Hardware/CH452.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Hardware/CH452.c.o
.PHONY : Hardware/CH452.c.o

Hardware/CH452.i: Hardware/CH452.c.i
.PHONY : Hardware/CH452.i

# target to preprocess a source file
Hardware/CH452.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Hardware/CH452.c.i
.PHONY : Hardware/CH452.c.i

Hardware/CH452.s: Hardware/CH452.c.s
.PHONY : Hardware/CH452.s

# target to generate assembly for a file
Hardware/CH452.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Hardware/CH452.c.s
.PHONY : Hardware/CH452.c.s

Hardware/Motor.o: Hardware/Motor.c.o
.PHONY : Hardware/Motor.o

# target to build an object file
Hardware/Motor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Hardware/Motor.c.o
.PHONY : Hardware/Motor.c.o

Hardware/Motor.i: Hardware/Motor.c.i
.PHONY : Hardware/Motor.i

# target to preprocess a source file
Hardware/Motor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Hardware/Motor.c.i
.PHONY : Hardware/Motor.c.i

Hardware/Motor.s: Hardware/Motor.c.s
.PHONY : Hardware/Motor.s

# target to generate assembly for a file
Hardware/Motor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Hardware/Motor.c.s
.PHONY : Hardware/Motor.c.s

Hardware/sys.o: Hardware/sys.c.o
.PHONY : Hardware/sys.o

# target to build an object file
Hardware/sys.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Hardware/sys.c.o
.PHONY : Hardware/sys.c.o

Hardware/sys.i: Hardware/sys.c.i
.PHONY : Hardware/sys.i

# target to preprocess a source file
Hardware/sys.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Hardware/sys.c.i
.PHONY : Hardware/sys.c.i

Hardware/sys.s: Hardware/sys.c.s
.PHONY : Hardware/sys.s

# target to generate assembly for a file
Hardware/sys.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Hardware/sys.c.s
.PHONY : Hardware/sys.c.s

Lib/src/misc.o: Lib/src/misc.c.o
.PHONY : Lib/src/misc.o

# target to build an object file
Lib/src/misc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Lib/src/misc.c.o
.PHONY : Lib/src/misc.c.o

Lib/src/misc.i: Lib/src/misc.c.i
.PHONY : Lib/src/misc.i

# target to preprocess a source file
Lib/src/misc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Lib/src/misc.c.i
.PHONY : Lib/src/misc.c.i

Lib/src/misc.s: Lib/src/misc.c.s
.PHONY : Lib/src/misc.s

# target to generate assembly for a file
Lib/src/misc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Lib/src/misc.c.s
.PHONY : Lib/src/misc.c.s

Lib/src/stm32f10x_adc.o: Lib/src/stm32f10x_adc.c.o
.PHONY : Lib/src/stm32f10x_adc.o

# target to build an object file
Lib/src/stm32f10x_adc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Lib/src/stm32f10x_adc.c.o
.PHONY : Lib/src/stm32f10x_adc.c.o

Lib/src/stm32f10x_adc.i: Lib/src/stm32f10x_adc.c.i
.PHONY : Lib/src/stm32f10x_adc.i

# target to preprocess a source file
Lib/src/stm32f10x_adc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Lib/src/stm32f10x_adc.c.i
.PHONY : Lib/src/stm32f10x_adc.c.i

Lib/src/stm32f10x_adc.s: Lib/src/stm32f10x_adc.c.s
.PHONY : Lib/src/stm32f10x_adc.s

# target to generate assembly for a file
Lib/src/stm32f10x_adc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Lib/src/stm32f10x_adc.c.s
.PHONY : Lib/src/stm32f10x_adc.c.s

Lib/src/stm32f10x_bkp.o: Lib/src/stm32f10x_bkp.c.o
.PHONY : Lib/src/stm32f10x_bkp.o

# target to build an object file
Lib/src/stm32f10x_bkp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Lib/src/stm32f10x_bkp.c.o
.PHONY : Lib/src/stm32f10x_bkp.c.o

Lib/src/stm32f10x_bkp.i: Lib/src/stm32f10x_bkp.c.i
.PHONY : Lib/src/stm32f10x_bkp.i

# target to preprocess a source file
Lib/src/stm32f10x_bkp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Lib/src/stm32f10x_bkp.c.i
.PHONY : Lib/src/stm32f10x_bkp.c.i

Lib/src/stm32f10x_bkp.s: Lib/src/stm32f10x_bkp.c.s
.PHONY : Lib/src/stm32f10x_bkp.s

# target to generate assembly for a file
Lib/src/stm32f10x_bkp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/Lib/src/stm32f10x_bkp.c.s
.PHONY : Lib/src/stm32f10x_bkp.c.s

User/main.o: User/main.c.o
.PHONY : User/main.o

# target to build an object file
User/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/User/main.c.o
.PHONY : User/main.c.o

User/main.i: User/main.c.i
.PHONY : User/main.i

# target to preprocess a source file
User/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/User/main.c.i
.PHONY : User/main.c.i

User/main.s: User/main.c.s
.PHONY : User/main.s

# target to generate assembly for a file
User/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/User/main.c.s
.PHONY : User/main.c.s

User/stm32f10x_it.o: User/stm32f10x_it.c.o
.PHONY : User/stm32f10x_it.o

# target to build an object file
User/stm32f10x_it.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/User/stm32f10x_it.c.o
.PHONY : User/stm32f10x_it.c.o

User/stm32f10x_it.i: User/stm32f10x_it.c.i
.PHONY : User/stm32f10x_it.i

# target to preprocess a source file
User/stm32f10x_it.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/User/stm32f10x_it.c.i
.PHONY : User/stm32f10x_it.c.i

User/stm32f10x_it.s: User/stm32f10x_it.c.s
.PHONY : User/stm32f10x_it.s

# target to generate assembly for a file
User/stm32f10x_it.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proj1.elf.dir/build.make CMakeFiles/proj1.elf.dir/User/stm32f10x_it.c.s
.PHONY : User/stm32f10x_it.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... proj1.bin"
	@echo "... proj1.hex"
	@echo "... proj1.elf"
	@echo "... CMSIS/core_cm3_linux.o"
	@echo "... CMSIS/core_cm3_linux.i"
	@echo "... CMSIS/core_cm3_linux.s"
	@echo "... CMSIS/system_stm32f10x.o"
	@echo "... CMSIS/system_stm32f10x.i"
	@echo "... CMSIS/system_stm32f10x.s"
	@echo "... Hardware/Bsp.o"
	@echo "... Hardware/Bsp.i"
	@echo "... Hardware/Bsp.s"
	@echo "... Hardware/CH452.o"
	@echo "... Hardware/CH452.i"
	@echo "... Hardware/CH452.s"
	@echo "... Hardware/Motor.o"
	@echo "... Hardware/Motor.i"
	@echo "... Hardware/Motor.s"
	@echo "... Hardware/sys.o"
	@echo "... Hardware/sys.i"
	@echo "... Hardware/sys.s"
	@echo "... Lib/src/misc.o"
	@echo "... Lib/src/misc.i"
	@echo "... Lib/src/misc.s"
	@echo "... Lib/src/stm32f10x_adc.o"
	@echo "... Lib/src/stm32f10x_adc.i"
	@echo "... Lib/src/stm32f10x_adc.s"
	@echo "... Lib/src/stm32f10x_bkp.o"
	@echo "... Lib/src/stm32f10x_bkp.i"
	@echo "... Lib/src/stm32f10x_bkp.s"
	@echo "... User/main.o"
	@echo "... User/main.i"
	@echo "... User/main.s"
	@echo "... User/stm32f10x_it.o"
	@echo "... User/stm32f10x_it.i"
	@echo "... User/stm32f10x_it.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

